service: sns-lambda-background-processing

provider:
  name: aws
  runtime: ruby2.5
  stage: dev
  region: ap-northeast-2
  environment:
    DB_HOST: [Your DB host]
    DB_USERNAME: [Your DB username]
    DB_PASSWORD: [Your DB password]
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ses:*
        - sns:*
      Resource: "*"

functions:
  example:
    handler: functions/example.handler
    events:
      - http:
          path: /
          method: post

  enqueue_pending_jobs:
    handler: functions/enqueue_pending_jobs.handler
    events:
      - schedule: rate(5 minutes)

  execute_pending_jobs:
    handler: functions/execute_pending_jobs.handler
    events:
      - sns: [Your SNS ARN]
