default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  port: 3306
  timeout: 5000
  database: sns_lambda_background_processing_example_db
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
